// Generates src/talks.generated.ts by embedding every talks/*.txt as an array
// of non-empty lines. Run via `prebuild` / `pretest` so a single-file binary
// (and the tests) don't need the talks/ folder on disk at runtime.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const talksDir = join(root, 'talks');

const talks = {};
for (const file of readdirSync(talksDir).filter((f) => f.endsWith('.txt'))) {
  const name = file.replace(/\.txt$/, '');
  talks[name] = readFileSync(join(talksDir, file), 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0);
}

const banner = '// AUTO-GENERATED by scripts/embed-talks.mjs — do not edit.\n';
const body = `export const TALKS: Record<string, string[]> = ${JSON.stringify(talks, null, 2)};\n`;
writeFileSync(join(root, 'src', 'talks.generated.ts'), banner + body);

console.log(`Embedded ${Object.keys(talks).length} talk script(s): ${Object.keys(talks).join(', ')}`);
